(cl:defpackage ad_challenge_msgs-msg
  (:use )
  (:export
   "<CM_OBJECT>"
   "CM_OBJECT"
   "<CAMERAINFO_MESSAGE>"
   "CAMERAINFO_MESSAGE"
   "<CONTROL_SIGNAL>"
   "CONTROL_SIGNAL"
   "<FULLSTATEBBOX3D>"
   "FULLSTATEBBOX3D"
   "<FULLSTATEBBOX3DARRAY>"
   "FULLSTATEBBOX3DARRAY"
   "<OB_LIST>"
   "OB_LIST"
   "<REGIONOFINTEREST>"
   "REGIONOFINTEREST"
   "<TRAFFICSIGN>"
   "TRAFFICSIGN"
   "<TRAFFICSIGNARRAY>"
   "TRAFFICSIGNARRAY"
   "<UAQ_OUT>"
   "UAQ_OUT"
  ))

