# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ad_challenge_msgs/FullStateBBox3D.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import vision_msgs.msg

class FullStateBBox3D(genpy.Message):
  _md5sum = "c9c7d008a4a47a5d05b55140b7b32d93"
  _type = "ad_challenge_msgs/FullStateBBox3D"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int64 id
vision_msgs/BoundingBox3D box

## velocity and acceleration for bounding-box location
geometry_msgs/Twist velocity
geometry_msgs/Accel acceleration

## velocity and acceleration for bounding-box size
geometry_msgs/Vector3 size_dot
geometry_msgs/Vector3 size_ddot
================================================================================
MSG: vision_msgs/BoundingBox3D
# A 3D bounding box that can be positioned and rotated about its center (6 DOF)
# Dimensions of this box are in meters, and as such, it may be migrated to
#   another package, such as geometry_msgs, in the future.

# The 3D position and orientation of the bounding box center
geometry_msgs/Pose center

# The size of the bounding box, in meters, surrounding the object's center
#   pose.
geometry_msgs/Vector3 size

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Accel
# This expresses acceleration in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular
"""
  __slots__ = ['id','box','velocity','acceleration','size_dot','size_ddot']
  _slot_types = ['int64','vision_msgs/BoundingBox3D','geometry_msgs/Twist','geometry_msgs/Accel','geometry_msgs/Vector3','geometry_msgs/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,box,velocity,acceleration,size_dot,size_ddot

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FullStateBBox3D, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.box is None:
        self.box = vision_msgs.msg.BoundingBox3D()
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Twist()
      if self.acceleration is None:
        self.acceleration = geometry_msgs.msg.Accel()
      if self.size_dot is None:
        self.size_dot = geometry_msgs.msg.Vector3()
      if self.size_ddot is None:
        self.size_ddot = geometry_msgs.msg.Vector3()
    else:
      self.id = 0
      self.box = vision_msgs.msg.BoundingBox3D()
      self.velocity = geometry_msgs.msg.Twist()
      self.acceleration = geometry_msgs.msg.Accel()
      self.size_dot = geometry_msgs.msg.Vector3()
      self.size_ddot = geometry_msgs.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_q28d().pack(_x.id, _x.box.center.position.x, _x.box.center.position.y, _x.box.center.position.z, _x.box.center.orientation.x, _x.box.center.orientation.y, _x.box.center.orientation.z, _x.box.center.orientation.w, _x.box.size.x, _x.box.size.y, _x.box.size.z, _x.velocity.linear.x, _x.velocity.linear.y, _x.velocity.linear.z, _x.velocity.angular.x, _x.velocity.angular.y, _x.velocity.angular.z, _x.acceleration.linear.x, _x.acceleration.linear.y, _x.acceleration.linear.z, _x.acceleration.angular.x, _x.acceleration.angular.y, _x.acceleration.angular.z, _x.size_dot.x, _x.size_dot.y, _x.size_dot.z, _x.size_ddot.x, _x.size_ddot.y, _x.size_ddot.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.box is None:
        self.box = vision_msgs.msg.BoundingBox3D()
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Twist()
      if self.acceleration is None:
        self.acceleration = geometry_msgs.msg.Accel()
      if self.size_dot is None:
        self.size_dot = geometry_msgs.msg.Vector3()
      if self.size_ddot is None:
        self.size_ddot = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 232
      (_x.id, _x.box.center.position.x, _x.box.center.position.y, _x.box.center.position.z, _x.box.center.orientation.x, _x.box.center.orientation.y, _x.box.center.orientation.z, _x.box.center.orientation.w, _x.box.size.x, _x.box.size.y, _x.box.size.z, _x.velocity.linear.x, _x.velocity.linear.y, _x.velocity.linear.z, _x.velocity.angular.x, _x.velocity.angular.y, _x.velocity.angular.z, _x.acceleration.linear.x, _x.acceleration.linear.y, _x.acceleration.linear.z, _x.acceleration.angular.x, _x.acceleration.angular.y, _x.acceleration.angular.z, _x.size_dot.x, _x.size_dot.y, _x.size_dot.z, _x.size_ddot.x, _x.size_ddot.y, _x.size_ddot.z,) = _get_struct_q28d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_q28d().pack(_x.id, _x.box.center.position.x, _x.box.center.position.y, _x.box.center.position.z, _x.box.center.orientation.x, _x.box.center.orientation.y, _x.box.center.orientation.z, _x.box.center.orientation.w, _x.box.size.x, _x.box.size.y, _x.box.size.z, _x.velocity.linear.x, _x.velocity.linear.y, _x.velocity.linear.z, _x.velocity.angular.x, _x.velocity.angular.y, _x.velocity.angular.z, _x.acceleration.linear.x, _x.acceleration.linear.y, _x.acceleration.linear.z, _x.acceleration.angular.x, _x.acceleration.angular.y, _x.acceleration.angular.z, _x.size_dot.x, _x.size_dot.y, _x.size_dot.z, _x.size_ddot.x, _x.size_ddot.y, _x.size_ddot.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.box is None:
        self.box = vision_msgs.msg.BoundingBox3D()
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Twist()
      if self.acceleration is None:
        self.acceleration = geometry_msgs.msg.Accel()
      if self.size_dot is None:
        self.size_dot = geometry_msgs.msg.Vector3()
      if self.size_ddot is None:
        self.size_ddot = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 232
      (_x.id, _x.box.center.position.x, _x.box.center.position.y, _x.box.center.position.z, _x.box.center.orientation.x, _x.box.center.orientation.y, _x.box.center.orientation.z, _x.box.center.orientation.w, _x.box.size.x, _x.box.size.y, _x.box.size.z, _x.velocity.linear.x, _x.velocity.linear.y, _x.velocity.linear.z, _x.velocity.angular.x, _x.velocity.angular.y, _x.velocity.angular.z, _x.acceleration.linear.x, _x.acceleration.linear.y, _x.acceleration.linear.z, _x.acceleration.angular.x, _x.acceleration.angular.y, _x.acceleration.angular.z, _x.size_dot.x, _x.size_dot.y, _x.size_dot.z, _x.size_ddot.x, _x.size_ddot.y, _x.size_ddot.z,) = _get_struct_q28d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_q28d = None
def _get_struct_q28d():
    global _struct_q28d
    if _struct_q28d is None:
        _struct_q28d = struct.Struct("<q28d")
    return _struct_q28d
