// Generated by gencpp from file ad_challenge_msgs/TrafficSignArray.msg
// DO NOT EDIT!


#ifndef AD_CHALLENGE_MSGS_MESSAGE_TRAFFICSIGNARRAY_H
#define AD_CHALLENGE_MSGS_MESSAGE_TRAFFICSIGNARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ad_challenge_msgs/TrafficSign.h>

namespace ad_challenge_msgs
{
template <class ContainerAllocator>
struct TrafficSignArray_
{
  typedef TrafficSignArray_<ContainerAllocator> Type;

  TrafficSignArray_()
    : header()
    , signs()  {
    }
  TrafficSignArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , signs(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::ad_challenge_msgs::TrafficSign_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ad_challenge_msgs::TrafficSign_<ContainerAllocator> >> _signs_type;
  _signs_type signs;





  typedef boost::shared_ptr< ::ad_challenge_msgs::TrafficSignArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ad_challenge_msgs::TrafficSignArray_<ContainerAllocator> const> ConstPtr;

}; // struct TrafficSignArray_

typedef ::ad_challenge_msgs::TrafficSignArray_<std::allocator<void> > TrafficSignArray;

typedef boost::shared_ptr< ::ad_challenge_msgs::TrafficSignArray > TrafficSignArrayPtr;
typedef boost::shared_ptr< ::ad_challenge_msgs::TrafficSignArray const> TrafficSignArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ad_challenge_msgs::TrafficSignArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ad_challenge_msgs::TrafficSignArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ad_challenge_msgs::TrafficSignArray_<ContainerAllocator1> & lhs, const ::ad_challenge_msgs::TrafficSignArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.signs == rhs.signs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ad_challenge_msgs::TrafficSignArray_<ContainerAllocator1> & lhs, const ::ad_challenge_msgs::TrafficSignArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ad_challenge_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ad_challenge_msgs::TrafficSignArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ad_challenge_msgs::TrafficSignArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ad_challenge_msgs::TrafficSignArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ad_challenge_msgs::TrafficSignArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ad_challenge_msgs::TrafficSignArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ad_challenge_msgs::TrafficSignArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ad_challenge_msgs::TrafficSignArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c876fa72bcd3a44f43d6f58a18d3409";
  }

  static const char* value(const ::ad_challenge_msgs::TrafficSignArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c876fa72bcd3a44ULL;
  static const uint64_t static_value2 = 0xf43d6f58a18d3409ULL;
};

template<class ContainerAllocator>
struct DataType< ::ad_challenge_msgs::TrafficSignArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad_challenge_msgs/TrafficSignArray";
  }

  static const char* value(const ::ad_challenge_msgs::TrafficSignArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ad_challenge_msgs::TrafficSignArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"ad_challenge_msgs/TrafficSign[] signs\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ad_challenge_msgs/TrafficSign\n"
"int64 id\n"
"float32[3] position\n"
"float32[3] vector\n"
;
  }

  static const char* value(const ::ad_challenge_msgs::TrafficSignArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ad_challenge_msgs::TrafficSignArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.signs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrafficSignArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ad_challenge_msgs::TrafficSignArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ad_challenge_msgs::TrafficSignArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "signs[]" << std::endl;
    for (size_t i = 0; i < v.signs.size(); ++i)
    {
      s << indent << "  signs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ad_challenge_msgs::TrafficSign_<ContainerAllocator> >::stream(s, indent + "    ", v.signs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AD_CHALLENGE_MSGS_MESSAGE_TRAFFICSIGNARRAY_H
